### ISSUE TITLE
Update superagent dependency version (known vulnerability)

### ISSUE THREAD

**Issue by westy92** [ngonzalvez/rest-facade#14]
Currently using superagent 1.8.5 which has an [underlying vulnerability](https://snyk.io/test/npm/rest-facade).

Please update to the latest version of superagent, ^3.5.2.

**Comment by ngonzalvez** [comment]
Nice catch! Thanks @westy92, it's updated in v1.5 now.

**Comment by westy92** [comment]
Thank you for the fix!
