### ISSUE TITLE
Proxy Support Needed

### ISSUE THREAD

**Issue by mostekcm** [ngonzalvez/rest-facade#16]
I am working on a CLI that uses the rest-facade and sometimes it is run behind corporate firewalls that need proxy access to the internet.  It would be great if this package could be updated to use this: https://www.npmjs.com/package/superagent-proxy so that it could be configured to use a proxy when making https requests.

**Comment by mostekcm** [comment]
If you want to see an example of how this was done in another package using superagent, see here: https://github.com/auth0/wt-cli/pull/123

**Comment by ngonzalvez** [comment]
Hi @mostekcm, thanks for taking the time to propose this. I'll add support for this in the next days.

**Comment by ngonzalvez** [comment]
@mostekcm this feature is now available in version 1.7.
