### ISSUE TITLE
Please update on NPM

### ISSUE THREAD

**Issue by jamiesoncj** [ngonzalvez/rest-facade#19]
Thank you for creating this excellent package.

I tried to use the new request customizer feature added in #18 but it seems that the latest GitHub master branch has not been published to NPM. Could you please bump the package version and update the NPM package?

Thank you!

**Comment by ngonzalvez** [comment]
Hi @jamiesoncj, I just released version 1.6 on NPM. This new version includes the feature you mentioned. I'm sorry for the delay.
