### ISSUE TITLE
Suggestion regarding Client methods for HTTP verbs

### ISSUE THREAD

**Issue by iamjochem** [ngonzalvez/rest-facade#24]
hi @ngonzalvez,

me again. I have a suggestion :

```js
// somewhere near the bottom of 'src/Client.js'
restClient.prototype.post = restClient.prototype.create;
restClient.prototype.put  = restClient.prototype.update;
```

the Client class already has a "get", "patch" and "delete" method, I think it would be nice if the list was completed with "post" & "put" so that all the HTTP verbs are represented.

what's your opinion?

**Comment by ngonzalvez** [comment]
Sounds good to me. I'll add it and release it as v1.8.

**Comment by ngonzalvez** [comment]
Ok, it's done. Now we have this feature in version 1.8. It's also tested and documented. Thanks @iamjochem!
