### ISSUE TITLE
HTTP DELETE - body sometimes required

### ISSUE THREAD

**Issue by iamjochem** [ngonzalvez/rest-facade#25]
hi there,

right now `delete()` methods don't accept a body (AFAICT), technically request bodies are not a thing but unfortunately there are APIs out there that require a body for certain DELETE endpoints.

it would be nice if `delete()` was less strict/correct and accepted a body parameter.

I came across this whilst using the [Auth0](auth0.com) API (actually I was working with their Authorization Extension API)  ... you may or may not be aware that Auth0 uses `rest-facade` in their [node client](https://github.com/auth0/node-auth0) ... actually this is the reason I we are using rest-facade internally (my colleague noticed it in Auth0's code and decided he like it).

**Comment by ngonzalvez** [comment]
Hi @iamjochem,

I'll change the delete method signature to be `delete(urlParams, body, callback)` with the last two arguments being optional.

And to answer you question: yes, I am aware of the Auth0 node client, I wrote most of its code. ;)

**Comment by iamjochem** [comment]
@ngonzalvez - I see ... and thanks. right now I've got a custom client, much like the Auth0 Management client, for the Auth0 Authorization Extension and I'm using the request customization functionality that your merged in to 'hack' the body into some of that API's DELETE endpoints :-).

**Comment by ngonzalvez** [comment]
This is available on version 1.10.0
