### ISSUE TITLE
Support asynchronous request customizer functions

### ISSUE THREAD

**Issue by jamiesoncj** [ngonzalvez/rest-facade#26]
The request customizer function is very useful but it would be even more useful to make it asynchronous, in case (for example) an authentication call should be made prior to each request (or a call for a cached auth token etc.) - this was my use case and I implemented a slightly nasty version of this [here](https://github.com/jamiesoncj/rest-facade/commit/9c3831fd682db3001efcd3de4a3c8aeab2555ecc) for my immediate need.

Would you consider allowing the request customiser to be asynchronous (either using a callback or promise)?

This change would mean the request customizer function would be passed with args `req, params, cb` and `cb` must be called in order for the request to be sent. If an argument is passed to `cb(err)`, it will be treated as an error and the request will not be sent.

Example:

```javascript
const options = {
      headers: {
        'User-agent': `node.js/${process.version.replace('v', '')}`,
        'Content-Type': 'application/json',
      },
      request: {
        customizer(req, params, cb) {
          getAuthTokenFromSomewhere(userId, secret)
            .then((token) => {
              req.set('Authorization', `Bearer ${token}`);
              return cb();
            })
            .catch((err) => {
              console.err('Some error occurred! ', err);
              return cb(err);
            });
        },
      },
    };

    this.Movie = new rest.Client('https://api.mydomain.com/v1/movies', options);
```

**Comment by iamjochem** [comment]
requiring that the callback be called will break existing usage,  it would be better to allow the customizer function to optionally return a promise, and if it does have the code wait on it.

**Comment by jamiesoncj** [comment]
@iamjochem thanks - did you take a look at the PR for this (#34)? If no callback is supplied the function is fun synchronously as per the existing behaviour. I believe this won't break existing functionality (the tests pass) but if you have an example case I'm happy to take a look.

**Comment by iamjochem** [comment]
@jamiesoncj - I hadn't seen the PR, you can indeed use the `length` of the function to sniff whether it wants a callback, but personally I feel that is a little more brittle that just allowing for an optional returned promise:

1. it makes it impossible, in the future, to add more arguments to the customizer without breaking existing usage
2. it will not work with spread operator usage
3. it will break for anyone that is/will accidently pass in a function that has extraneous parameters defined.

**Comment by ngonzalvez** [comment]
I agree that allowing customizer functions to return an optional promise would be the best way to go. It would allow the user to use the async/await.
