### ISSUE TITLE
superagent gzip DoS vulnerability

### ISSUE THREAD

**Issue by masaruhoshi** [ngonzalvez/rest-facade#32]
There is a report about a DoS vulnerability on `superagent` that may make some components vulnerable. 

https://nodesecurity.io/advisories/479

I have PR #31 bumping up superagent to a recommended version.

**Comment by luisrudge** [comment]
we're also depending on this on https://github.com/auth0/node-auth0/issues/207

**Comment by ngonzalvez** [comment]
It's fixed on version 1.10.1
