### ISSUE TITLE
string request bodies not allowed

### ISSUE THREAD

**Issue by iamjochem** [ngonzalvez/rest-facade#35]
hi there,

I have a process that handles a (rabbitmq) message queue and uses rest-facade to perform a POST for each item in the queue (based on some message meta-data) ... each message contains a JSON serialized string that is meant to be the payload/body of the given POST request.

I would like to be able to pass in the payload/body string as-is rather than having to use `JSON.parse()` on the string before hand - deserializing a JSON string just so I can pass it into rest-facade is wasteful given that rest-facade (actually `superagent`) just re-serializes the data in order to perform a request.

Currently rest-facade does not allow this because of [this check](https://github.com/ngonzalvez/rest-facade/blob/master/src/Client.js#L119). 

I am wondering whether it is necessary for rest-facade to require that request body data is in object form?

**Comment by ngonzalvez** [comment]
I think we can add support for request body in a string format. The only reason I used objects is because it is handy for most situations, but adding support for strings wouldn't hurt at all.

**Comment by iamjochem** [comment]
@ngonzalvez - indeed, Objects is mostly what you deal with - allowing strings (presumably JSON strings) would just be an optimalization in the case that someone already had a JSON string at hand.

please take a look at the PR I made if/when you have time ... there is one major question that needs to be considered, namely whether you intend rest-facade should deal onyl with JSON requests/responses or not ... if you think it should then a `req.type('json')` call should(?) be applied in order to force a JSON content-type header (in the case of `data` being given as a string) ... or the docs need to make clear that a "request customizer" needs to be used in order to set the content-type of the request correctly.
