### ISSUE TITLE
Update superagent-proxy version to 2.0.0

### ISSUE THREAD

**Issue by maxpaj** [ngonzalvez/rest-facade#38]
socks@1.1.10 which is a package down the dependency graph from superagent-proxy is deprecated. Upgrade superagent-proxy to avoid the install warning.

`npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0`

**Comment by ngonzalvez** [comment]
Updated in version 1.10.2.
