### ISSUE TITLE
getAll with single params object as an argument does not transport params

### ISSUE THREAD

**Issue by asilluron** [ngonzalvez/rest-facade#4]
Looks like a typo at https://github.com/ngonzalvez/rest-facade/blob/master/src/Client.js#L50

**Comment by ngonzalvez** [comment]
The above commit fixes it, but test is still pending. Once tested, we can close this.

**Comment by iamstarkov** [comment]
so its fixed?

**Comment by ngonzalvez** [comment]
Yes. It's fixed but not tested yet. I'll try to find time today to add the corresponding tests so that we can close this.
