### ISSUE TITLE
Promise.resolve should only take one argument

### ISSUE THREAD

**Issue by hornta** [ngonzalvez/rest-facade#59]
Hello. I found this piece of code which concerns me a bit since Promise.resolve can only take one argument. https://github.com/ngonzalvez/rest-facade/blob/master/src/Client.js#L425

**Comment by ngonzalvez** [comment]
Yes, you are right. I'll fix it in a PR. Thanks for the heads up.

**Comment by ngonzalvez** [comment]
This is fixed, I'm closing this.
