### ISSUE TITLE
Add support for case convertion for the body of the response

### ISSUE THREAD

**Issue by ngonzalvez** [ngonzalvez/rest-facade#6]
Right now only case convertion of the query-string params is supported. Rest-facade should provide a way to convert this response:

```javascript
{
  user_id: 1,
  first_name: 'John',
  last_name: 'Doe'
}
```
into this:
```javascript
{
  userId: 1,
  firstName: 'John',
  lastName: 'Doe'
}
```

**Comment by iamstarkov** [comment]
seems to be fixed

> You can solve this problem by specifing a naming convention when creating the Rest Client. The naming convention can be any of snakeCase, camelCase, pascalCase, paramCase, or any other implemented by the change-case library.
> — from docs

**Comment by ngonzalvez** [comment]
The current implementation only does the conversion for query params. However the conversion for the body of the request/response is still not implemented.
