### ISSUE TITLE
superagent-proxy still required

### ISSUE THREAD

**Issue by briangeorge** [ngonzalvez/rest-facade#63]
Client.js still has a dependency on superagent-proxy on line 38.  Is this intended?

Having the require on line 38 means that Webpack tries to replace it with a useful require, but it fails because it was removed as a dependency from rest-facade.

**Comment by KurtMar** [comment]
I have hit this bug when bundling with esbuild in AWS CDK: node_modules/formidable/lib/incoming_form.js: warning: Indirect calls to "require" will not be bundled (surround with a try/catch to silence this warning)

I just included it in my project's package.json as a dependency for now.

**Comment by ngonzalvez** [comment]
`v1.16.3` has been released with @shomukai's PR. Please confirm if this solves it for everyone.

**Comment by stevenbdf** [comment]
@ngonzalvez It does not. superagent-proxy is still required. As it throws an error when bundling using webpack for AWS Serverless. 

```
ERROR in ../../../rest-facade/src/Client.js 38:4-31
Module not found: Error: Can't resolve 'superagent-proxy' in '...\node_modules\rest-facade\src'
```

**Comment by ngonzalvez** [comment]
@stevenbdf are you setting a value for the [proxy setting](https://github.com/ngonzalvez/rest-facade#proxy-support) when initializing the `rest-facade` instance?

**Comment by shomukai** [comment]
@stevenbdf , we are using https://github.com/dougmoscrop/serverless-plugin-include-dependencies for AWS serverless. If you are using webpack, you need to set alias to false mentioned above.
```
resolve: {
  alias: {
    'superagent-proxy': false
  }
}
```

**Comment by maccoda** [comment]
For those facing the same issue with `esbuild` you can use the [external](https://esbuild.github.io/api/#external) option to tell it that it does not require it as part of the bundle.
